version: '3.4'
services:
    backend:
        container_name: PlanningPoker-Backend
        restart: always
        image: planningpokerbackend
        environment:
            - DOMAIN=${DOMAIN}
            - BACKEND_PORT=${BACKEND_PORT}
        build:
            target: backend
            dockerfile: Dockerfile
            context: .
        ports:
            - "8080:8080"
    frontend:
        restart: always
        container_name: PlanningPoker-Frontend
        image: planningpokerfrontend
        ports:
            - "80:80"
        build:
            target: frontend
            dockerfile: Dockerfile
            context: .
            args:
                - TRAEFIK=${TRAEFIK}
                - DOMAIN=${DOMAIN}
                - PRODUCTION=${PRODUCTION}
                - PROTOCOL=${PROTOCOL}
                - BACKEND_PORT=${BACKEND_PORT}