apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: planning-poker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
