name: deploy to test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TRAEFIK: "true"
      TRAEFIK_CERT_RESOLVER: "HttpsResolver"
      TRAEFIK_ENTRYPOINT: "Https"
      TRAEFIK_NETWORK: "Frontend"
      TRAEFIK_ROUTER: "PlanningPokerRouter"
      CONTAINER_NAME: "planning-poker"
      IMAGE_NAME: "planningpoker"
      DOMAIN: ${{ secrets.DOMAIN }}
      PRODUCTION: "true"
      PROTOCOL: "https"
      BACKEND_PORT: "80"
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: TRAEFIK,TRAEFIK_CERT_RESOLVER,TRAEFIK_ENTRYPOINT,TRAEFIK_NETWORK,TRAEFIK_ROUTER,CONTAINER_NAME,IMAGE_NAME,DOMAIN,PRODUCTION,PROTOCOL,BACKEND_PORT
        script: |
          cd PlanningPoker
          git pull
          docker compose -f traefik.docker-compose.yml build
          docker compose -f traefik.docker-compose.yml down
          docker compose -f traefik.docker-compose.yml up -d --force-recreate
